"""empty message

Revision ID: 4b735dcbc700
Revises: ec29e100e925
Create Date: 2018-07-11 06:11:22.348123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b735dcbc700'
down_revision = 'ec29e100e925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.Column('whoUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('adminID'),
    sa.UniqueConstraint('username')
    )
    op.create_table('brand_info',
    sa.Column('brandID', sa.Integer(), nullable=False),
    sa.Column('brandName', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.Column('whoUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('brandID')
    )
    op.create_table('challenge_desc',
    sa.Column('challengeID', sa.Integer(), nullable=False),
    sa.Column('challengeProblem', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.Column('whoUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('challengeID')
    )
    op.drop_table('users')
    op.add_column('challenges', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('challengeLanguage', sa.String(length=150), nullable=True))
    op.add_column('challenges', sa.Column('challengeLevel', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('challenges', sa.Column('lastUpdate', sa.DateTime(), nullable=True))
    op.add_column('challenges', sa.Column('whoUpdate', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('brandID', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brandName', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('created', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('lastUpdate', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('productPoints', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('whoUpdate', sa.DateTime(), nullable=True))
    op.add_column('profile', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('profile', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('profile', sa.Column('lastUpdate', sa.DateTime(), nullable=True))
    op.add_column('profile', sa.Column('profileID', sa.Integer(), nullable=False))
    op.add_column('profile', sa.Column('whoUpdate', sa.DateTime(), nullable=True))
    op.drop_column('profile', 'profileid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profileid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('profile', 'whoUpdate')
    op.drop_column('profile', 'profileID')
    op.drop_column('profile', 'lastUpdate')
    op.drop_column('profile', 'created')
    op.drop_column('profile', 'active')
    op.drop_column('products', 'whoUpdate')
    op.drop_column('products', 'productPoints')
    op.drop_column('products', 'lastUpdate')
    op.drop_column('products', 'created')
    op.drop_column('products', 'brandName')
    op.drop_column('products', 'brandID')
    op.drop_column('products', 'active')
    op.drop_column('challenges', 'whoUpdate')
    op.drop_column('challenges', 'lastUpdate')
    op.drop_column('challenges', 'created')
    op.drop_column('challenges', 'challengeLevel')
    op.drop_column('challenges', 'challengeLanguage')
    op.drop_column('challenges', 'active')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.drop_table('challenge_desc')
    op.drop_table('brand_info')
    op.drop_table('admin')
    # ### end Alembic commands ###
