"""empty message

Revision ID: 4fabfad5a0c2
Revises: de56a2254ea0
Create Date: 2018-07-08 04:07:44.835341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fabfad5a0c2'
down_revision = 'de56a2254ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_points',
    sa.Column('pointid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pointid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_points')
    # ### end Alembic commands ###
