"""empty message

Revision ID: 9c42c16eb820
Revises: d02bc8c6ce6e
Create Date: 2018-07-15 09:38:14.629250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c42c16eb820'
down_revision = 'd02bc8c6ce6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('contactName', sa.String(length=200), nullable=True))
    op.add_column('brands', sa.Column('contactNumber', sa.String(length=50), nullable=True))
    op.add_column('brands', sa.Column('emailID', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'emailID')
    op.drop_column('brands', 'contactNumber')
    op.drop_column('brands', 'contactName')
    # ### end Alembic commands ###
