"""empty message

Revision ID: de56a2254ea0
Revises: f5451a296359
Create Date: 2018-07-04 20:35:34.867658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de56a2254ea0'
down_revision = 'f5451a296359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('challengeID', sa.Integer(), nullable=False),
    sa.Column('challengeName', sa.String(length=150), nullable=True),
    sa.Column('challengePoints', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('challengeID')
    )
    op.create_table('products',
    sa.Column('productiD', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('productiD')
    )
    op.create_table('profile',
    sa.Column('profileid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('profileid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('profile')
    op.drop_table('products')
    op.drop_table('challenges')
    # ### end Alembic commands ###
